import turtle
turtle.Screen().bgcolor('black')
t=turtle.Turtle()
t.speed(0)
t.hideturtle()

for i in range(120):
    t.color('red')
    t.circle(i)
    t.color('orange')
    t.circle(i*0.50)
    t.right(3)
    t.forward(3)
    t.right(3)
    t.forward(3)
    t.right(3)
    t.forward(3)
    t.right(3)
    t.forward(3)
turtle.done()